import { authorize, id, operationalDb } from "../_lib/operations";

export const dynamic="force-dynamic";

export async function GET(req:Request){const auth=await authorize(req,["sales","finance","academy","viewer"]);if(!auth.ok)return auth.response;const db=operationalDb();const {results}=await db.prepare("SELECT r.*,c.name customer_name,p.name program_name FROM seat_reservations r JOIN customers c ON c.id=r.customer_id JOIN programs p ON p.id=r.program_id ORDER BY r.created_at DESC").all();return Response.json({reservations:results})}

export async function POST(req:Request){
 const auth=await authorize(req,["sales","finance","academy"]);if(!auth.ok)return auth.response;
 const body=await req.json() as Record<string,unknown>,action=String(body.action||""),db=operationalDb(),now=new Date().toISOString();
 if(action==="request_transfer"){
  if(!auth.roles.includes("admin")&&!auth.roles.includes("sales"))return Response.json({error:"هذا الإجراء للمبيعات"},{status:403});
  const fromId=String(body.reservationId||""),targetProgramId=String(body.targetProgramId||"");
  const reservation=await db.prepare("SELECT status FROM seat_reservations WHERE id=?").bind(fromId).first<{status:string}>();
  if(!reservation||reservation.status!=="مؤكد")return Response.json({error:"الحجز غير قابل للنقل"},{status:409});
  const transferId=id("TRN");await db.batch([db.prepare("INSERT INTO reservation_transfers(id,from_reservation_id,target_program_id,target_cohort_label,status,requested_by_email,requested_at) VALUES(?,?,?,?,'بانتظار المالية',?,?)").bind(transferId,fromId,targetProgramId,String(body.targetCohortLabel||""),auth.email,now),db.prepare("UPDATE seat_reservations SET status='نقل قيد المراجعة',updated_at=? WHERE id=?").bind(now,fromId),db.prepare("INSERT INTO workflow_tasks(id,entity_type,entity_id,department,title,status,priority,created_by_email,created_at) VALUES(?,'reservation_transfer',?,'المالية','مراجعة نقل حجز المقعد','مفتوحة','عالية',?,?)").bind(id("TSK"),transferId,auth.email,now),db.prepare("INSERT INTO audit_log(id,actor_email,action,entity_type,entity_id,details,created_at) VALUES(?,?,'REQUEST_RESERVATION_TRANSFER','reservation_transfer',?,?,?)").bind(id("AUD"),auth.email,transferId,JSON.stringify({fromId,targetProgramId}),now)]);return Response.json({ok:true,transferId},{status:201});
 }
 if(action==="review_transfer"){
  if(!auth.roles.includes("admin")&&!auth.roles.includes("finance"))return Response.json({error:"هذا الإجراء للمالية"},{status:403});
  const transferId=String(body.transferId||""),decision=String(body.decision||"");const transfer=await db.prepare("SELECT t.*,r.customer_id,r.order_id,r.fee_amount FROM reservation_transfers t JOIN seat_reservations r ON r.id=t.from_reservation_id WHERE t.id=?").bind(transferId).first<Record<string,unknown>>();
  if(!transfer||transfer.status!=="بانتظار المالية")return Response.json({error:"طلب النقل غير متاح"},{status:409});
  if(decision==="reject"){await db.batch([db.prepare("UPDATE reservation_transfers SET status='مرفوض',reviewed_by_finance_email=?,reviewed_at=?,financial_decision=? WHERE id=?").bind(auth.email,now,String(body.financialDecision||""),transferId),db.prepare("UPDATE seat_reservations SET status='مؤكد',updated_at=? WHERE id=?").bind(now,transfer.from_reservation_id),db.prepare("UPDATE workflow_tasks SET status='مكتملة',completed_at=? WHERE entity_type='reservation_transfer' AND entity_id=?").bind(now,transferId)]);return Response.json({ok:true,status:"مرفوض"});}
  if(decision!=="approve")return Response.json({error:"القرار غير صالح"},{status:400});
  const newId=id("RSV");await db.batch([db.prepare("INSERT INTO seat_reservations(id,customer_id,program_id,order_id,fee_amount,status,cohort_label,confirmed_at,created_at,updated_at) VALUES(?,?,?,?,?,'مؤكد',?,?,?,?)").bind(newId,transfer.customer_id,transfer.target_program_id,transfer.order_id,transfer.fee_amount,transfer.target_cohort_label,now,now,now),db.prepare("UPDATE seat_reservations SET status='تم النقل',updated_at=? WHERE id=?").bind(now,transfer.from_reservation_id),db.prepare("UPDATE reservation_transfers SET to_reservation_id=?,status='تمت المعالجة',reviewed_by_finance_email=?,reviewed_at=?,financial_decision=? WHERE id=?").bind(newId,auth.email,now,String(body.financialDecision||""),transferId),db.prepare("UPDATE workflow_tasks SET status='مكتملة',completed_at=? WHERE entity_type='reservation_transfer' AND entity_id=?").bind(now,transferId),db.prepare("INSERT INTO audit_log(id,actor_email,action,entity_type,entity_id,details,created_at) VALUES(?,?,'APPROVE_RESERVATION_TRANSFER','reservation_transfer',?,?,?)").bind(id("AUD"),auth.email,transferId,JSON.stringify({newReservationId:newId,financialDecision:body.financialDecision}),now)]);return Response.json({ok:true,status:"تمت المعالجة",reservationId:newId});
 }
 if(action==="convert_to_enrollment"){
  const reservationId=String(body.reservationId||"");const reservation=await db.prepare("SELECT * FROM seat_reservations WHERE id=?").bind(reservationId).first<Record<string,unknown>>();if(!reservation||reservation.status!=="مؤكد")return Response.json({error:"الحجز غير جاهز للتحويل"},{status:409});
  const enrollmentId=id("ENR");await db.batch([db.prepare("INSERT INTO enrollments(id,customer_id,program_id,order_id,source_reservation_id,status,created_at,updated_at) VALUES(?,?,?,?,?,'جديد',?,?)").bind(enrollmentId,reservation.customer_id,reservation.program_id,reservation.order_id,reservationId,now,now),db.prepare("UPDATE seat_reservations SET status='تم التحويل',converted_enrollment_id=?,updated_at=? WHERE id=?").bind(enrollmentId,now,reservationId),db.prepare("INSERT INTO workflow_tasks(id,entity_type,entity_id,department,title,status,priority,created_by_email,created_at) VALUES(?,'enrollment',?,'الأكاديمية','التواصل مع العميل وبدء التسجيل','مفتوحة','عالية',?,?)").bind(id("TSK"),enrollmentId,auth.email,now),db.prepare("INSERT INTO audit_log(id,actor_email,action,entity_type,entity_id,details,created_at) VALUES(?,?,'CONVERT_RESERVATION','enrollment',?,?,?)").bind(id("AUD"),auth.email,enrollmentId,JSON.stringify({reservationId}),now)]);return Response.json({ok:true,enrollmentId});
 }
 return Response.json({error:"الإجراء غير صالح"},{status:400});
}
