import { authorize, ensureDirectProgramSchema, id, operationalDb, promoteDueReservations } from "../_lib/operations";

export const dynamic="force-dynamic";

export async function GET(req:Request){const auth=await authorize(req,["sales","finance","academy","viewer"]);if(!auth.ok)return auth.response;const db=operationalDb();await ensureDirectProgramSchema(db);await promoteDueReservations(db,auth.email);const kind=new URL(req.url).searchParams.get("kind");const base="SELECT r.*,c.name customer_name,c.phone,c.email,p.name program_name,t.id transfer_id,t.status transfer_status,t.target_cohort_label,t.requested_at transfer_requested_at,tp.name target_program_name FROM seat_reservations r JOIN customers c ON c.id=r.customer_id JOIN programs p ON p.id=r.program_id JOIN orders o ON o.id=r.order_id LEFT JOIN reservation_transfers t ON t.id=(SELECT rt.id FROM reservation_transfers rt WHERE rt.from_reservation_id=r.id ORDER BY rt.requested_at DESC LIMIT 1) LEFT JOIN programs tp ON tp.id=t.target_program_id";const query=base+(kind==="seat"?" WHERE o.seat_reservation=1 AND r.fee_amount>0 AND r.reservation_kind IN ('حجز مقعد','حجز مقعد فقط','حجز مع تسجيل')":kind?" WHERE r.reservation_kind=?":"")+" ORDER BY r.created_at DESC";const prepared=db.prepare(query);const {results}=kind&&kind!=="seat"?await prepared.bind(kind).all():await prepared.all();return Response.json({reservations:results})}

export async function POST(req:Request){
 const auth=await authorize(req,["sales","finance","academy"]);if(!auth.ok)return auth.response;
 const body=await req.json() as Record<string,unknown>,action=String(body.action||""),db=operationalDb(),now=new Date().toISOString();
 if(action==="withdraw_seat_only"){
  if(!auth.roles.includes("admin")&&!auth.roles.includes("sales"))return Response.json({error:"هذا الإجراء للمبيعات"},{status:403});
  const reservationId=String(body.reservationId||"");
  const reservation=await db.prepare("SELECT customer_id,order_id,reservation_kind,status FROM seat_reservations WHERE id=?").bind(reservationId).first<{customer_id:string;order_id:string;reservation_kind:string;status:string}>();
  if(!reservation||reservation.reservation_kind!=="حجز مقعد فقط"||reservation.status==="منسحب")return Response.json({error:"الحجز غير متاح للانسحاب"},{status:409});
  await db.batch([db.prepare("UPDATE seat_reservations SET status='منسحب',updated_at=? WHERE id=?").bind(now,reservationId),db.prepare("UPDATE customers SET customer_type='منسحب',updated_at=? WHERE id=?").bind(now,reservation.customer_id),db.prepare("UPDATE orders SET status='منسحب',academy_status='غير مطبق',updated_at=? WHERE id=?").bind(now,reservation.order_id),db.prepare("UPDATE workflow_tasks SET status='مكتملة',completed_at=? WHERE entity_type='reservation' AND entity_id=?").bind(now,reservationId),db.prepare("INSERT INTO audit_log(id,actor_email,action,entity_type,entity_id,details,created_at) VALUES(?,?,'WITHDRAW_SEAT_ONLY','seat_reservation',?,'{}',?)").bind(id("AUD"),auth.email,reservationId,now)]);
  return Response.json({ok:true,status:"منسحب"});
 }
 if(action==="complete_seat_only"){
  if(!auth.roles.includes("admin")&&!auth.roles.includes("sales"))return Response.json({error:"هذا الإجراء للمبيعات"},{status:403});
  const reservationId=String(body.reservationId||""),baseTotal=Math.round(Number(body.baseTotal||0)*100)/100,discount=Number(body.discountPercent||0),paymentPlan=String(body.paymentPlan||"دفع كامل"),firstPayment=Math.round(Number(body.firstPayment||0)*100)/100;
  const total=Math.round(baseTotal*(1-discount/100)*100)/100,paid=paymentPlan==="أقساط"?firstPayment:total;
  if(!(baseTotal>0)||!(total>0)||!(paid>0)||(paymentPlan==="أقساط"&&paid>=total))return Response.json({error:"تحقق من قيمة البرنامج والدفعة الأولى"},{status:400});
  const reservation=await db.prepare("SELECT * FROM seat_reservations WHERE id=?").bind(reservationId).first<Record<string,unknown>>();
  if(!reservation||reservation.reservation_kind!=="حجز مقعد فقط"||reservation.status==="منسحب"||reservation.converted_enrollment_id)return Response.json({error:"الحجز غير متاح للاستكمال"},{status:409});
  const enrollmentId=id("ENR"),paymentId=id("PAY"),needsReview=paymentPlan==="أقساط";
  const statements=[db.prepare("UPDATE seat_reservations SET reservation_kind='حجز مع تسجيل',status='مسجل',converted_enrollment_id=?,updated_at=? WHERE id=?").bind(enrollmentId,now,reservationId),db.prepare("UPDATE customers SET customer_type='مسجل',updated_at=? WHERE id=?").bind(now,reservation.customer_id),db.prepare("UPDATE orders SET payment_plan=?,base_total=?,discount_percent=?,total=?,paid=?,status=?,academy_status='تم التواصل',finance_review_status=?,updated_at=? WHERE id=?").bind(paymentPlan,baseTotal,discount,total,paid,paymentPlan==="أقساط"?"مدفوع جزئياً":"مدفوع",needsReview?"pending":"approved",now,reservation.order_id),db.prepare("INSERT INTO payments(id,order_id,amount,paid_at,status,method,reference,flow_type,classification_status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(paymentId,reservation.order_id,paid,now,"مسجلة",String(body.method||"دفع مباشر"),String(body.reference||""),"sale",needsReview?"pending":"confirmed",now),db.prepare("INSERT INTO enrollments(id,customer_id,program_id,order_id,source_reservation_id,status,created_at,updated_at) VALUES(?,?,?,?,?,'تم التواصل',?,?)").bind(enrollmentId,reservation.customer_id,reservation.program_id,reservation.order_id,reservationId,now,now),db.prepare("UPDATE workflow_tasks SET status='مكتملة',completed_at=? WHERE entity_type='reservation' AND entity_id=?").bind(now,reservationId),db.prepare("INSERT INTO workflow_tasks(id,entity_type,entity_id,department,title,status,priority,created_by_email,created_at) VALUES(?,'enrollment',?,'التشغيلية','تهيئة العميل واستكمال بياناته','مفتوحة','عالية',?,?)").bind(id("TSK"),enrollmentId,auth.email,now),db.prepare("INSERT INTO audit_log(id,actor_email,action,entity_type,entity_id,details,created_at) VALUES(?,?,'COMPLETE_SEAT_ONLY','enrollment',?,?,?)").bind(id("AUD"),auth.email,enrollmentId,JSON.stringify({reservationId,baseTotal,discount,total,paid,paymentPlan}),now)];
  if(needsReview)statements.push(db.prepare("INSERT INTO workflow_tasks(id,entity_type,entity_id,department,title,status,priority,created_by_email,created_at) VALUES(?,'payment',?,'المالية','اعتماد وتنظيم طلب أقساط','مفتوحة','عالية',?,?)").bind(id("TSK"),paymentId,auth.email,now));
  await db.batch(statements);return Response.json({ok:true,status:"مسجل",enrollmentId});
 }
 if(action==="schedule_start"){
  const reservationId=String(body.reservationId||""),cohortLabel=String(body.cohortLabel||"").trim(),startDate=String(body.startDate||""),assignmentDate=String(body.assignmentDate||"");
  if(!reservationId||!cohortLabel||!/^\d{4}-\d{2}-\d{2}$/.test(startDate)||!/^\d{4}-\d{2}-\d{2}$/.test(assignmentDate))return Response.json({error:"اسم الدفعة وتاريخ البدء وتاريخ الإسناد مطلوبة"},{status:400});
  if(assignmentDate>startDate)return Response.json({error:"تاريخ الإسناد يجب أن يكون في تاريخ بدء البرنامج أو قبله"},{status:400});
  const reservation=await db.prepare("SELECT order_id,status FROM seat_reservations WHERE id=?").bind(reservationId).first<{order_id:string,status:string}>();
  if(!reservation||!["مؤكد","بانتظار البدء","بانتظار الإسناد"].includes(reservation.status))return Response.json({error:"الحجز غير متاح للجدولة"},{status:409});
  await db.batch([db.prepare("UPDATE seat_reservations SET cohort_label=?,start_date=?,assignment_date=?,status='بانتظار الإسناد',updated_at=? WHERE id=?").bind(cohortLabel,startDate,assignmentDate,now,reservationId),db.prepare("UPDATE orders SET cohort_label=?,scheduled_start_date=?,updated_at=? WHERE id=?").bind(cohortLabel,startDate,now,reservation.order_id),db.prepare("INSERT INTO audit_log(id,actor_email,action,entity_type,entity_id,details,created_at) VALUES(?,?,'SCHEDULE_RESERVATION_START','seat_reservation',?,?,?)").bind(id("AUD"),auth.email,reservationId,JSON.stringify({cohortLabel,startDate,assignmentDate}),now)]);
  await promoteDueReservations(db,auth.email);
  return Response.json({ok:true,status:"بانتظار الإسناد"});
 }
 if(action==="request_transfer"){
  if(!auth.roles.includes("admin")&&!auth.roles.includes("sales"))return Response.json({error:"هذا الإجراء للمبيعات"},{status:403});
  const fromId=String(body.reservationId||""),targetProgramId=String(body.targetProgramId||"");
  const reservation=await db.prepare("SELECT status FROM seat_reservations WHERE id=?").bind(fromId).first<{status:string}>();
  if(!reservation||reservation.status!=="مؤكد")return Response.json({error:"الحجز غير قابل للنقل"},{status:409});
  const transferId=id("TRN");await db.batch([db.prepare("INSERT INTO reservation_transfers(id,from_reservation_id,target_program_id,target_cohort_label,status,requested_by_email,requested_at) VALUES(?,?,?,?,'بانتظار المالية',?,?)").bind(transferId,fromId,targetProgramId,String(body.targetCohortLabel||""),auth.email,now),db.prepare("UPDATE seat_reservations SET status='نقل قيد المراجعة',updated_at=? WHERE id=?").bind(now,fromId),db.prepare("INSERT INTO workflow_tasks(id,entity_type,entity_id,department,title,status,priority,created_by_email,created_at) VALUES(?,'reservation_transfer',?,'المالية','مراجعة نقل حجز المقعد','مفتوحة','عالية',?,?)").bind(id("TSK"),transferId,auth.email,now),db.prepare("INSERT INTO audit_log(id,actor_email,action,entity_type,entity_id,details,created_at) VALUES(?,?,'REQUEST_RESERVATION_TRANSFER','reservation_transfer',?,?,?)").bind(id("AUD"),auth.email,transferId,JSON.stringify({fromId,targetProgramId}),now)]);return Response.json({ok:true,transferId},{status:201});
 }
 if(action==="review_transfer"){
  if(!auth.roles.includes("admin")&&!auth.roles.includes("finance"))return Response.json({error:"هذا الإجراء للمالية"},{status:403});
  const transferId=String(body.transferId||""),decision=String(body.decision||"");const transfer=await db.prepare("SELECT t.*,r.customer_id,r.order_id,r.fee_amount FROM reservation_transfers t JOIN seat_reservations r ON r.id=t.from_reservation_id WHERE t.id=?").bind(transferId).first<Record<string,unknown>>();
  if(!transfer||transfer.status!=="بانتظار المالية")return Response.json({error:"طلب النقل غير متاح"},{status:409});
  if(decision==="reject"){await db.batch([db.prepare("UPDATE reservation_transfers SET status='مرفوض',reviewed_by_finance_email=?,reviewed_at=?,financial_decision=? WHERE id=?").bind(auth.email,now,String(body.financialDecision||""),transferId),db.prepare("UPDATE seat_reservations SET status='مؤكد',updated_at=? WHERE id=?").bind(now,transfer.from_reservation_id),db.prepare("UPDATE workflow_tasks SET status='مكتملة',completed_at=? WHERE entity_type='reservation_transfer' AND entity_id=?").bind(now,transferId)]);return Response.json({ok:true,status:"مرفوض"});}
  if(decision!=="approve")return Response.json({error:"القرار غير صالح"},{status:400});
  const newId=id("RSV");await db.batch([db.prepare("INSERT INTO seat_reservations(id,customer_id,program_id,order_id,fee_amount,status,cohort_label,confirmed_at,created_at,updated_at) VALUES(?,?,?,?,?,'مؤكد',?,?,?,?)").bind(newId,transfer.customer_id,transfer.target_program_id,transfer.order_id,transfer.fee_amount,transfer.target_cohort_label,now,now,now),db.prepare("UPDATE seat_reservations SET status='تم النقل',updated_at=? WHERE id=?").bind(now,transfer.from_reservation_id),db.prepare("UPDATE reservation_transfers SET to_reservation_id=?,status='تمت المعالجة',reviewed_by_finance_email=?,reviewed_at=?,financial_decision=? WHERE id=?").bind(newId,auth.email,now,String(body.financialDecision||""),transferId),db.prepare("UPDATE workflow_tasks SET status='مكتملة',completed_at=? WHERE entity_type='reservation_transfer' AND entity_id=?").bind(now,transferId),db.prepare("INSERT INTO audit_log(id,actor_email,action,entity_type,entity_id,details,created_at) VALUES(?,?,'APPROVE_RESERVATION_TRANSFER','reservation_transfer',?,?,?)").bind(id("AUD"),auth.email,transferId,JSON.stringify({newReservationId:newId,financialDecision:body.financialDecision}),now)]);return Response.json({ok:true,status:"تمت المعالجة",reservationId:newId});
 }
 if(action==="convert_to_enrollment"){
  const reservationId=String(body.reservationId||"");const reservation=await db.prepare("SELECT * FROM seat_reservations WHERE id=?").bind(reservationId).first<Record<string,unknown>>();if(!reservation||reservation.status!=="بانتظار البدء"||!reservation.start_date)return Response.json({error:"حدّد الدفعة وتاريخ البدء قبل تحويل الحجز"},{status:409});
  const enrollmentId=id("ENR");await db.batch([db.prepare("INSERT INTO enrollments(id,customer_id,program_id,order_id,source_reservation_id,status,started_at,created_at,updated_at) VALUES(?,?,?,?,?,'تم التواصل',?,?,?)").bind(enrollmentId,reservation.customer_id,reservation.program_id,reservation.order_id,reservationId,now,now,now),db.prepare("UPDATE seat_reservations SET status='تم التحويل',converted_enrollment_id=?,updated_at=? WHERE id=?").bind(enrollmentId,now,reservationId),db.prepare("UPDATE orders SET order_type=CASE WHEN order_type='إشراف' THEN 'إشراف' ELSE 'برنامج' END,academy_status='تم التواصل',cohort_label=?,updated_at=? WHERE id=?").bind(reservation.cohort_label||null,now,reservation.order_id),db.prepare("UPDATE workflow_tasks SET status='مكتملة',completed_at=? WHERE entity_type='reservation' AND entity_id=? AND status!='مكتملة'").bind(now,reservationId),db.prepare("INSERT INTO workflow_tasks(id,entity_type,entity_id,department,title,status,priority,created_by_email,created_at) VALUES(?,'enrollment',?,'التشغيلية','تهيئة العميل واستكمال بياناته','مفتوحة','عالية',?,?)").bind(id("TSK"),enrollmentId,auth.email,now),db.prepare("INSERT INTO audit_log(id,actor_email,action,entity_type,entity_id,details,created_at) VALUES(?,?,'CONVERT_RESERVATION','enrollment',?,?,?)").bind(id("AUD"),auth.email,enrollmentId,JSON.stringify({reservationId,cohort:reservation.cohort_label,startDate:reservation.start_date}),now)]);return Response.json({ok:true,enrollmentId});
 }
 return Response.json({error:"الإجراء غير صالح"},{status:400});
}
