import {env} from "cloudflare:workers";
import {NextResponse} from "next/server";
export const dynamic="force-dynamic";
async function init(){const db=env.DB;await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS customers (id TEXT PRIMARY KEY, name TEXT NOT NULL, phone TEXT NOT NULL UNIQUE, email TEXT NOT NULL UNIQUE, customer_type TEXT NOT NULL DEFAULT 'مسجل', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT)"),
 db.prepare("CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, customer_id TEXT NOT NULL, program TEXT NOT NULL, track TEXT NOT NULL, delivery TEXT NOT NULL, language TEXT NOT NULL, purchase_source TEXT NOT NULL, payment_plan TEXT NOT NULL, total REAL NOT NULL DEFAULT 0, paid REAL NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'جديد', academy_status TEXT NOT NULL, owner TEXT NOT NULL DEFAULT 'غير مسند', competency INTEGER NOT NULL DEFAULT 0, seat_reservation INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(customer_id) REFERENCES customers(id))"),
 db.prepare("CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY, order_id TEXT NOT NULL, department TEXT NOT NULL, title TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'مفتوحة', assignee TEXT, due_at TEXT, created_at TEXT NOT NULL, completed_at TEXT, FOREIGN KEY(order_id) REFERENCES orders(id))"),
 db.prepare("CREATE TABLE IF NOT EXISTS audit_log (id TEXT PRIMARY KEY, actor_email TEXT NOT NULL, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, details TEXT, created_at TEXT NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS orders_customer_idx ON orders(customer_id)"),db.prepare("CREATE INDEX IF NOT EXISTS orders_program_idx ON orders(program)"),db.prepare("CREATE INDEX IF NOT EXISTS tasks_order_idx ON tasks(order_id)")]);return db}
export async function GET(){try{const db=await init();const {results}=await db.prepare("SELECT c.id,c.name,c.phone,c.email,o.id order_id,o.program,o.track,o.purchase_source source,o.owner,o.academy_status state,o.paid,o.total FROM customers c JOIN orders o ON o.customer_id=c.id WHERE c.deleted_at IS NULL ORDER BY o.created_at DESC").all();return NextResponse.json({customers:results})}catch{return NextResponse.json({customers:[],offline:true})}}
export async function POST(req:Request){try{const db=await init();const body=await req.json() as Record<string,unknown>;const name=String(body.name||"").trim(),phone=String(body.phone||"").replace(/\s/g,""),email=String(body.email||"").trim().toLowerCase();if(!name||!phone||!email)return NextResponse.json({error:"الاسم والجوال والبريد حقول إلزامية"},{status:400});const duplicate=await db.prepare("SELECT id FROM customers WHERE phone=? OR email=? LIMIT 1").bind(phone,email).first();if(duplicate)return NextResponse.json({error:"يوجد عميل مسجل بنفس الجوال أو البريد"},{status:409});const now=new Date().toISOString(),customerId=`CUS-${crypto.randomUUID().slice(0,8)}`,orderId=`SLK-${Date.now().toString().slice(-6)}`,asara=body.source==="عصارة",academyStatus=asara?"مكتمل":"بانتظار الإضافة";const jobs:Array<{d:string;t:string}>=[];if(!asara)jobs.push({d:"الأكاديمية",t:"إضافة العميل إلى منصة عصارة"},{d:"الأكاديمية",t:"إسناد المقررات"});if(body.competency)jobs.push({d:"الأكاديمية",t:"إضافة خدمة تقييم الكفاءة"},{d:"الأكاديمية",t:"ربط العميل وإسناده للمشرف"});jobs.push({d:"المالية",t:`متابعة ${String(body.payment||"الدفع")}`});await db.batch([db.prepare("INSERT INTO customers(id,name,phone,email,customer_type,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").bind(customerId,name,phone,email,String(body.customerType||"مسجل"),now,now),db.prepare("INSERT INTO orders(id,customer_id,program,track,delivery,language,purchase_source,payment_plan,total,paid,academy_status,competency,seat_reservation,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(orderId,customerId,String(body.program||""),String(body.track||""),String(body.delivery||""),String(body.language||""),String(body.source||""),String(body.payment||""),Number(body.amount||0),0,academyStatus,body.competency?1:0,body.seat?1:0,now,now),...jobs.map(j=>db.prepare("INSERT INTO tasks(id,order_id,department,title,created_at) VALUES(?,?,?,?,?)").bind(crypto.randomUUID(),orderId,j.d,j.t,now)),db.prepare("INSERT INTO audit_log(id,actor_email,action,entity_type,entity_id,details,created_at) VALUES(?,?,?,?,?,?,?)").bind(crypto.randomUUID(),req.headers.get("oai-authenticated-user-email")||"local@system","CREATE","order",orderId,JSON.stringify({source:body.source,program:body.program}),now)]);return NextResponse.json({ok:true,customerId,orderId,tasks:jobs.length},{status:201})}catch(e){return NextResponse.json({error:"تعذر حفظ التسجيل",details:e instanceof Error?e.message:"unknown"},{status:500})}}
