"use client";
import { useMemo, useState } from "react";

type View="dashboard"|"work"|"customers"|"academy"|"finance"|"reports"|"new";
type NavItem=[View,string,string,number?];
const navGroups:{label:string,items:NavItem[]}[]=[
 {label:"الرئيسية",items:[["dashboard","لوحة القيادة","⌂"],["work","عملي اليوم","✓",8]]},
 {label:"إدارة العملاء",items:[["customers","العملاء والتسجيلات","◎"]]},
 {label:"العمليات",items:[["academy","عمليات الأكاديمية","◫",5],["finance","المالية والتحصيل","﷼",3]]},
 {label:"التحليلات",items:[["reports","التقارير","↗"]]}
];
const initialPeople=[
 {id:"SLK-2048",name:"سارة محمد",phone:"055 321 9840",program:"تحليل السلوك التطبيقي",track:"ABAT",source:"المتجر",owner:"ليان",state:"بانتظار التسجيل",tone:"amber",due:"متابعة اليوم، 12:30 م",paid:4250,total:6500},
 {id:"SLK-2047",name:"عمر خالد",phone:"050 918 3721",program:"إدارة السلوك التنظيمي",track:"P",source:"تسجيل مباشر",owner:"نور",state:"بانتظار الإسناد",tone:"blue",due:"منذ ساعتين",paid:8000,total:8000},
 {id:"SLK-2046",name:"ريم عبدالله",phone:"053 645 2280",program:"تحليل السلوك التطبيقي",track:"QBA",source:"المنصة",owner:"ليان",state:"تم التواصل",tone:"violet",due:"متابعة غداً",paid:3000,total:9500},
 {id:"SLK-2045",name:"فيصل أحمد",phone:"056 122 8304",program:"التعليم المستمر",track:"RBT",source:"تمارا",owner:"مها",state:"مكتمل",tone:"green",due:"لا إجراء مطلوب",paid:2400,total:2400},
 {id:"SLK-2044",name:"نجلاء صالح",phone:"054 827 1036",program:"الاقتصاد السلوكي",track:"برنامج الممارس",source:"عصارة",owner:"نور",state:"مكتمل",tone:"green",due:"تم التفعيل تلقائياً",paid:3200,total:3200},
 {id:"SLK-2043",name:"هدى إبراهيم",phone:"057 422 6951",program:"الاقتصاد السلوكي",track:"التصميم السلوكي",source:"سلة",owner:"ليان",state:"بانتظار الإسناد",tone:"blue",due:"إسناد اليوم",paid:1500,total:3000},
 {id:"SLK-2042",name:"محمد القحطاني",phone:"059 731 2840",program:"الاقتصاد السلوكي",track:"برنامج الممارس",source:"دفع مباشر",owner:"مها",state:"تم التواصل",tone:"violet",due:"متابعة غداً",paid:1000,total:3200}
];
const people=initialPeople;
const tasks=[
 ["09:30","التواصل مع سارة لاستكمال التسجيل","سارة محمد · SLK-2048","أكاديمية","amber"],
 ["11:00","التحقق من الدفعة الثانية","ريم عبدالله · 2,000 ر.س","مالية","red"],
 ["12:30","إسناد مقررات برنامج OBM","عمر خالد · الدفعة 18","إسناد","blue"],
 ["14:00","مراجعة طلب جديد من المتجر","نجلاء صالح · SLK-2049","مبيعات","violet"]
];
const titles:Record<View,[string,string]>={dashboard:["صباح الخير، أحمد","هذه صورة العمل الحية ليوم الثلاثاء 21 يوليو"],work:["عملي اليوم","الأولويات والمتابعات المسندة إليك"],customers:["العملاء والتسجيلات","ملف موحد لكل عميل وجميع تسجيلاته"],academy:["عمليات الأكاديمية","من الاستلام حتى التحقق من دخول المتعلم"],finance:["المالية والتحصيل","المستحقات، الدفعات وخطط الأقساط"],reports:["التقارير الإدارية","مؤشرات الأداء وجودة العمليات"],new:["تسجيل عميل جديد","سجّل الطلب مرة واحدة وسيُنشئ النظام إجراءات الأقسام تلقائياً"]};

export default function Home(){
 const[view,setView]=useState<View>("dashboard"),[query,setQuery]=useState(""),[people,setPeople]=useState(initialPeople),[selected,setSelected]=useState(initialPeople[0]),[panel,setPanel]=useState(false);
 const list=useMemo(()=>people.filter(p=>`${p.name} ${p.id} ${p.program}`.includes(query)),[query]);
 const open=(p:typeof initialPeople[number])=>{setSelected(p);setPanel(true)};
 const updateWorkflow=(state:string,tone:string,due:string)=>{Object.assign(selected,{state,tone,due});setSelected({...selected});setPeople([...people])};
 return <main className="shell" dir="rtl">
  <aside className="sidebar"><div className="brand"><i>س</i><div><b>سلوكيرا</b><span>مركز العمليات</span></div></div><div className="workspace"><i/><div><b>بيئة العمل</b><span>متصل وآمن</span></div><em>⌄</em></div><nav>{navGroups.map(group=><section className="nav-group" key={group.label}><p className="nav-label">{group.label}</p>{group.items.map(([id,label,icon,badge])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><i>{icon}</i>{label}{badge&&<em>{badge}</em>}</button>)}</section>)}</nav><div className="health"><span>سلامة النظام</span><b>كل الأنظمة تعمل</b><strong>99.9%</strong><i><u/></i></div><div className="profile"><i>أع</i><div><b>أحمد العلي</b><span>مدير النظام</span></div><button>⋯</button></div></aside>
  <section className="main"><header className="topbar"><b className="mobile-logo">سلوكيرا</b><label><i>⌕</i><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن عميل، رقم طلب أو برنامج..."/></label><button className="bell">♢<i/></button><button className="primary" onClick={()=>setView("new")}>＋ تسجيل جديد</button></header><div className="content"><header className="heading"><div><h1>{titles[view][0]}</h1><p>{titles[view][1]}</p></div><span>اليوم · 21 يوليو 2026</span></header>
   {view==="dashboard"&&<Dashboard open={open}/>} {view==="work"&&<Work/>} {view==="customers"&&<Customers list={list} open={open}/>} {view==="academy"&&<Academy open={open}/>} {view==="finance"&&<Finance open={open}/>} {view==="reports"&&<Reports/>} {view==="new"&&<Registration done={()=>setView("customers")}/>} 
  </div></section>
  {panel&&<><div className="overlay" onClick={()=>setPanel(false)}/><aside className="drawer"><button className="close" onClick={()=>setPanel(false)}>×</button><div className="person"><i>{selected.name.slice(0,2)}</i><div><h2>{selected.name}</h2><p>{selected.id} · {selected.phone}</p></div></div><div className="actions"><button>واتساب</button><button>اتصال</button><button>تعديل</button></div><Section title="التسجيل الحالي"><div className="info"><label>البرنامج<b>{selected.program}</b></label><label>المسار<b>{selected.track}</b></label><label>قناة الشراء<b>{selected.source}</b></label><label>المسؤول<b>{selected.owner}</b></label></div></Section><Section title="حالة الأكاديمية"><div className={`status ${selected.tone}`}><b>{selected.state}</b><span>{selected.due}</span></div><div className="workflow-actions"><button className={selected.state==="تم التواصل"?"current":""} onClick={()=>updateWorkflow("تم التواصل","violet","بانتظار إكمال التسجيل")}>✓ تم التواصل</button><button className={selected.state==="بانتظار الإسناد"?"current":""} onClick={()=>updateWorkflow("بانتظار الإسناد","blue","جاهز لإسناد المقررات")}>✓ اكتمل التسجيل</button><button className={selected.state==="مكتمل"?"current":""} onClick={()=>updateWorkflow("مكتمل","green","تم الإسناد والتحقق من الدخول")}>✓ تم الإسناد</button></div><p className="workflow-help">اختاري الإجراء الذي تم فعلياً، وستنتقل البطاقة إلى حالتها الجديدة.</p></Section><Section title="الملخص المالي"><div className="money"><p>قيمة الطلب<b>{selected.total.toLocaleString()} ر.س</b></p><p>المحصل<b>{selected.paid.toLocaleString()} ر.س</b></p></div><div className="progress"><i style={{width:`${selected.paid/selected.total*100}%`}}/></div></Section><Section title="آخر النشاطات"><div className="timeline"><p>تم تحديث حالة التسجيل<small>الآن · {selected.owner}</small></p><p>تم إنشاء التسجيل في النظام<small>أمس، 16:20 · المبيعات</small></p></div></Section></aside></>}
 </main>
}

function Dashboard({open}:{open:(p:typeof people[number])=>void}){return <><div className="kpis"><Kpi title="طلبات هذا الشهر" value="128" tag="+12.5%" note="مقارنة بالشهر الماضي" tone="blue"/><Kpi title="بانتظار الأكاديمية" value="17" tag="5 عاجلة" note="تجاوزت وقت الاستلام" tone="amber"/><Kpi title="التحصيل هذا الشهر" value="184,250" tag="ر.س" note="من أصل 221,000 ر.س" tone="green"/><Kpi title="مستحقات متأخرة" value="23,500" tag="8 أقساط" note="تحتاج متابعة مالية" tone="red"/></div><div className="dashboard-grid"><Card title="الأولويات اليوم" action="عرض كل المهام"><TaskList/></Card><Card title="تدفق عمليات الأكاديمية" action="فتح لوحة الأكاديمية"><div className="flow">{[["17","جديد","gray"],["12","تم التواصل","violet"],["9","بانتظار التسجيل","amber"],["6","بانتظار الإسناد","blue"],["84","مكتمل","green"]].map(([n,l,t])=><div key={l}><i className={t}>{n}</i><span>{l}</span></div>)}</div><div className="sla"><span>متوسط إكمال التهيئة</span><b>1.8 يوم</b><em>الهدف: أقل من يومين</em></div></Card><div className="latest"><Card title="أحدث التسجيلات" action="عرض جميع التسجيلات"><CustomerTable list={people} open={open}/></Card></div><Card title="نبض التحصيل" action="التفاصيل المالية"><div className="ring"><div><b>83%</b><span>نسبة التحصيل</span></div></div><div className="legend"><p><i className="green"/>تم التحصيل<b>184,250 ر.س</b></p><p><i className="amber"/>قادم<b>13,250 ر.س</b></p><p><i className="red"/>متأخر<b>23,500 ر.س</b></p></div></Card></div></>}
function Work(){return <div className="board">{["متأخرة","اليوم","قادمة"].map((col,i)=><section key={col}><header><b>{col}</b><span>{[2,4,7][i]}</span></header>{tasks.slice(i===2?1:0,i===0?2:4).map(t=><article key={t[1]}><em className={t[4]}>{t[3]}</em><h3>{t[1]}</h3><p>{t[2]}</p><footer>◷ {t[0]}<i>{i===1?"ن":"ل"}</i></footer></article>)}</section>)}</div>}
function Customers({list,open}:{list:typeof people,open:(p:typeof people[number])=>void}){
 const[program,setProgram]=useState("الكل"),[source,setSource]=useState("الكل"),[status,setStatus]=useState("الكل");
 const programs=["الكل",...Array.from(new Set(people.map(p=>p.program)))];
 const sources=["الكل",...Array.from(new Set(people.map(p=>p.source)))];
 const filtered=list.filter(p=>(program==="الكل"||p.program===program)&&(source==="الكل"||p.source===source)&&(status==="الكل"||(status==="مكتمل"?p.state==="مكتمل":p.state!=="مكتمل")));
 const active=program!=="الكل"||source!=="الكل"||status!=="الكل";
 return <><div className="customer-summary"><div><span>إجمالي العملاء</span><b>{people.length}</b></div><div><span>النتائج المعروضة</span><b>{filtered.length}</b></div><div><span>برامج نشطة</span><b>{new Set(people.map(p=>p.program)).size}</b></div><div><span>يحتاجون إجراء</span><b>{people.filter(p=>p.state!=="مكتمل").length}</b></div></div><div className="card full customer-directory"><div className="directory-head"><div><h2>دليل العملاء</h2><p>ابحث من الشريط العلوي أو خصّص القائمة باستخدام التصفيات.</p></div>{active&&<button onClick={()=>{setProgram("الكل");setSource("الكل");setStatus("الكل")}}>× مسح التصفيات</button>}</div><div className="directory-filters"><label><span>البرنامج</span><select value={program} onChange={e=>setProgram(e.target.value)}>{programs.map(x=><option key={x}>{x}</option>)}</select></label><label><span>مصدر الشراء</span><select value={source} onChange={e=>setSource(e.target.value)}>{sources.map(x=><option key={x}>{x}</option>)}</select></label><label><span>حالة الملف</span><select value={status} onChange={e=>setStatus(e.target.value)}><option>الكل</option><option>نشط</option><option>مكتمل</option></select></label><div className="result-count"><b>{filtered.length}</b><span>عميل مطابق</span></div></div>{filtered.length?<CustomerTable list={filtered} open={open}/>:<div className="empty-results"><i>⌕</i><b>لا توجد نتائج مطابقة</b><p>جرّب تغيير البرنامج أو مصدر الشراء.</p></div>}</div></>
}
function Academy({open}:{open:(p:typeof people[number])=>void}){return <div className="kanban">{["جديد","تم التواصل","بانتظار التسجيل","بانتظار الإسناد","مكتمل"].map((col,i)=><section key={col}><header><b>{col}</b><span>{i===4?84:[3,2,2,1][i]}</span></header>{people.filter((_,n)=>i===4?n===3:n===i).map(p=><article key={p.id} onClick={()=>open(p)}><b>{p.name}</b><small>{p.id}</small><p>{p.program}</p><em>{p.due}</em><footer><span>{p.track}</span><i>{p.owner[0]}</i></footer></article>)}</section>)}</div>}
function Finance({open}:{open:(p:typeof people[number])=>void}){return <><div className="kpis"><Kpi title="إجمالي المستحق" value="221,000" tag="ر.س" note="الشهر الحالي" tone="blue"/><Kpi title="تم التحصيل" value="184,250" tag="83%" note="من إجمالي المستحق" tone="green"/><Kpi title="قادم خلال 7 أيام" value="13,250" tag="6 أقساط" note="تذكير تلقائي مجدول" tone="amber"/><Kpi title="متأخر" value="23,500" tag="8 أقساط" note="3 تحتاج تصعيد" tone="red"/></div><Card title="متابعة الأقساط" action="تصدير التقرير"><div className="table-wrap"><table><thead><tr><th>العميل</th><th>الطلب</th><th>المبلغ</th><th>الاستحقاق</th><th>الحالة</th><th/></tr></thead><tbody>{people.map((p,i)=><tr key={p.id}><td><b>{p.name}</b><small>{p.phone}</small></td><td>{p.id}</td><td><b>{["2,250","2,000","1,500","—"][i]} ر.س</b></td><td>{["اليوم","متأخر 3 أيام","27 يوليو","مسدد"][i]}</td><td><span className={`pill ${["amber","red","blue","green"][i]}`}>{["مستحق اليوم","متأخر","قادم","مسدد"][i]}</span></td><td><button className="link" onClick={()=>open(p)}>فتح الملف</button></td></tr>)}</tbody></table></div></Card></>}
function Reports(){return <div className="reports"><Card title="التسجيلات حسب البرنامج" action="آخر 30 يوم"><div className="bars">{[["تحليل السلوك التطبيقي",74],["إدارة السلوك التنظيمي",52],["التعليم المستمر",31],["الاقتصاد السلوكي",18]].map(([n,v])=><div key={n}><span>{n}</span><i><u style={{width:`${v}%`}}/></i><b>{v}</b></div>)}</div></Card><Card title="كفاءة رحلة التسجيل" action="هذا الشهر"><div className="metric"><b>1.8</b><span>يوم متوسط التهيئة</span><em>↓ 14% تحسن</em></div><div className="mini"><p><b>4.2 س</b>أول تواصل</p><p><b>91%</b>إكمال التسجيل</p><p><b>96%</b>دقة البيانات</p></div></Card></div>}

function Registration({done}:{done:()=>void}){
 const[step,setStep]=useState(1),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState("");
 const[form,setForm]=useState({name:"",phone:"",email:"",journey:"شراء برنامج",program:"تحليل السلوك التطبيقي",track:"ABAT",delivery:"مسجل",language:"العربية",source:"عصارة",payment:"دفع كامل",method:"تحويل بنكي",amount:""});
 const set=(key:string,value:string|boolean)=>setForm(f=>({...f,[key]:value}));
 const asara=form.source==="عصارة";
 const submit=async()=>{setSaveError("");if(!form.name||!form.phone||!form.email){setSaveError("أكمل الاسم والجوال والبريد قبل الحفظ");setStep(1);return}const programIds:Record<string,string>={"تحليل السلوك التطبيقي":"PRG-ABA","إدارة السلوك التنظيمي":"PRG-OBM","الاقتصاد السلوكي":"PRG-BE","التعليم المستمر":"PRG-CE","تقييم الكفاءة":"PRG-COMP"};setSaving(true);try{const payload={...form,programId:programIds[form.program],mode:form.journey==="تجربة"?"trial":"payment",purchaseType:form.journey==="حجز مقعد"?"حجز مقعد":"برنامج"};const r=await fetch("/api/intake",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.error||"تعذر الحفظ");setSaved(true)}catch(e){setSaveError(e instanceof Error?e.message:"تعذر الحفظ في قاعدة البيانات")}finally{setSaving(false)}};
 const steps=["بيانات العميل","البرنامج والخدمة","الشراء والمالية","المراجعة"];
 if(saved)return <div className="register-success"><i>✓</i><h2>تم تسليم الطلب للعمليات</h2><p>{form.journey==="تجربة"?"بدأت التجربة وتم إنشاء مهمة متابعة للمبيعات.":form.journey==="حجز مقعد"?"تم إنشاء العميل وتأكيد حجز المقعد ومهمة المتابعة.":"تم إنشاء العميل والطلب والتسجيل ومهام الأكاديمية والمالية."}</p><div><button className="secondary" onClick={()=>setSaved(false)}>طلب جديد</button><button className="primary" onClick={done}>فتح قائمة العملاء</button></div></div>;
 return <div className="register-layout"><aside className="stepper">{steps.map((s,i)=><button key={s} className={step===i+1?"current":step>i+1?"complete":""} onClick={()=>setStep(i+1)}><i>{step>i+1?"✓":i+1}</i><span><b>{s}</b><small>{["الهوية ووسائل التواصل","اختيار المسار والتفاصيل","المصدر وخطة السداد","تدقيق وإنشاء الإجراءات"][i]}</small></span></button>)}</aside><section className="form-card">
  {step===1&&<><FormHead n="01" title="بيانات الطلب" text="اختاري سبب دخول الشخص للنظام؛ الدفع أو التجربة هما بوابة إنشاء العميل."/><div className="field-grid"><Field label="اسم العميل الكامل *"><input value={form.name} onChange={e=>set("name",e.target.value)} placeholder="مثال: سارة محمد العتيبي"/></Field><Field label="رقم الجوال *"><input value={form.phone} onChange={e=>set("phone",e.target.value)} placeholder="05xxxxxxxx"/></Field><Field label="البريد الإلكتروني *"><input value={form.email} onChange={e=>set("email",e.target.value)} placeholder="name@example.com"/></Field><Field label="نوع الرحلة"><select value={form.journey} onChange={e=>set("journey",e.target.value)}><option>شراء برنامج</option><option>حجز مقعد</option><option>تجربة</option></select></Field></div><div className="hint">لن يُنشأ العميل إلا عند تسجيل دفعة أو منحه تجربة من المبيعات.</div></>}
  {step===2&&<><FormHead n="02" title="البرنامج" text="تقييم الكفاءة برنامج مستقل، وحجز المقعد يحدد من نوع الرحلة في الخطوة السابقة."/><div className="field-grid"><Field label="البرنامج *"><select value={form.program} onChange={e=>set("program",e.target.value)}><option>تحليل السلوك التطبيقي</option><option>إدارة السلوك التنظيمي</option><option>الاقتصاد السلوكي</option><option>التعليم المستمر</option><option>تقييم الكفاءة</option></select></Field><Field label="المسار"><select value={form.track} onChange={e=>set("track",e.target.value)}>{form.program==="إدارة السلوك التنظيمي"?<><option>P</option><option>E</option><option>C</option></>:<><option>ABAT</option><option>QASP-S</option><option>QBA</option></>}</select></Field><Field label="نمط البرنامج"><select value={form.delivery} onChange={e=>set("delivery",e.target.value)}><option>مسجل</option><option>مباشر</option></select></Field><Field label="اللغة"><select value={form.language} onChange={e=>set("language",e.target.value)}><option>العربية</option><option>الإنجليزية</option></select></Field></div></>}
  {step===3&&<><FormHead n="03" title="الدفع" text={form.journey==="تجربة"?"التجربة لا تحتاج دفعة أو موافقة إدارية.":"تسجيل الإيصال ينشئ العميل فوراً؛ المالية تطابق العملية لاحقاً."}/><div className="source-grid">{["عصارة","سلة","دفع مباشر","تمارا","أخرى"].map(x=><button key={x} className={form.source===x?"selected":""} onClick={()=>set("source",x)}><i>{x==="عصارة"?"ع":x==="سلة"?"س":"◈"}</i><b>{x}</b><small>{x==="عصارة"?"تفعيل تلقائي":x==="تمارا"?"تقسيط خارجي":"مصدر الطلب"}</small></button>)}</div>{form.journey!=="تجربة"&&<div className="field-grid"><Field label="وسيلة الدفع"><select value={form.method} onChange={e=>set("method",e.target.value)}><option>تحويل بنكي</option><option>دفع إلكتروني</option><option>تمارا</option><option>نقدي</option></select></Field><Field label={form.journey==="حجز مقعد"?"رسوم حجز المقعد":"المبلغ المدفوع"}><input value={form.amount} onChange={e=>set("amount",e.target.value)} placeholder="0.00 ر.س"/></Field><Field label="خطة السداد"><select value={form.payment} onChange={e=>set("payment",e.target.value)}><option>دفع كامل</option><option>أقساط</option><option>تمارا</option></select></Field></div>}<div className={`automation-note ${form.journey==="تجربة"?"auto":"manual"}`}><i>✓</i><div><b>{form.journey==="تجربة"?"ستبدأ التجربة مباشرة":"لا يوجد انتظار لاعتماد المالية"}</b><p>{form.journey==="تجربة"?"سيحسب النظام مدة التجربة من إعداد البرنامج وينشئ متابعة للمبيعات.":"ستنشأ مهمة تنظيم ومطابقة للمالية دون تعطيل رحلة العميل."}</p></div></div></>}
  {step===4&&<><FormHead n="04" title="مراجعة الطلب" text="راجع نوع الرحلة والإجراءات التي سيُنشئها النظام قبل الحفظ."/><div className="review-grid"><section><h3>ملخص الطلب</h3><Review label="العميل" value={form.name||"لم يُدخل بعد"}/><Review label="نوع الرحلة" value={form.journey}/><Review label="البرنامج" value={`${form.program} · ${form.track}`}/><Review label="نمط الدراسة" value={`${form.delivery} · ${form.language}`}/><Review label="مصدر الشراء" value={form.source}/>{form.journey!=="تجربة"&&<><Review label="وسيلة الدفع" value={form.method}/><Review label="السداد" value={`${form.payment}${form.amount?` · ${form.amount} ر.س`:""}`}/></>}</section><section className="workflow-preview"><h3>الإجراءات التي ستُنشأ</h3><p className="done"><i>✓</i><span><b>{form.journey==="تجربة"?"إنشاء عميل تجربة":"إنشاء العميل والطلب فوراً"}</b><small>المبيعات · فوري</small></span></p>{form.journey==="تجربة"?<p className="next"><i>2</i><span><b>بدء التجربة وإنشاء المتابعة</b><small>المبيعات · حسب مدة البرنامج</small></span></p>:form.journey==="حجز مقعد"?<p className="next"><i>2</i><span><b>تأكيد الحجز ومتابعة موعد البدء</b><small>لا ينشئ تسجيلاً أكاديمياً الآن</small></span></p>:<><p className={asara?"done":"next"}><i>{asara?"✓":"2"}</i><span><b>{asara?"تفعيل الدورة تلقائياً عبر عصارة":"بدء رحلة التسجيل الأكاديمي"}</b><small>{asara?"لا يحتاج تدخلاً يدوياً":"الأكاديمية"}</small></span></p>{!asara&&<p className="next"><i>3</i><span><b>التواصل ثم إنشاء الحساب والإسناد</b><small>الأكاديمية</small></span></p>}</>} {form.journey!=="تجربة"&&<p className="finance-step"><i>ر.س</i><span><b>مطابقة وتنظيم الدفعة</b><small>المالية · لا تعطل رحلة العميل</small></span></p>}</section></div></>}
  {saveError&&<div className="save-error">{saveError}</div>}<footer className="wizard-actions"><button className="secondary" onClick={()=>step>1?setStep(step-1):done()}>{step>1?"السابق":"إلغاء"}</button><span>الخطوة {step} من 4</span>{step<4?<button className="primary" onClick={()=>setStep(step+1)}>التالي</button>:<button className="primary" disabled={saving} onClick={submit}>{saving?"جارٍ الحفظ...":"حفظ وتسليم للأقسام"}</button>}</footer>
 </section></div>
}
function FormHead({n,title,text}:{n:string,title:string,text:string}){return <header className="form-head"><i>{n}</i><div><h2>{title}</h2><p>{text}</p></div></header>}
function Field({label,children}:{label:string,children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Review({label,value}:{label:string,value:string}){return <p className="review-row"><span>{label}</span><b>{value}</b></p>}

function Kpi({title,value,tag,note,tone}:{title:string,value:string,tag:string,note:string,tone:string}){return <article className={`kpi ${tone}`}><span>{title}</span><div><b>{value}</b><em>{tag}</em></div><p>{note}</p></article>}
function Card({title,action,children}:{title:string,action:string,children:React.ReactNode}){return <section className="card"><header className="card-head"><h2>{title}</h2><button>{action} ←</button></header>{children}</section>}
function Section({title,children}:{title:string,children:React.ReactNode}){return <section className="drawer-section"><h3>{title}</h3>{children}</section>}
function TaskList(){return <div>{tasks.map(t=><div className="task" key={t[1]}><time>{t[0]}</time><i className={t[4]}/><div><b>{t[1]}</b><span>{t[2]}</span></div><em className={t[4]}>{t[3]}</em><button>⋯</button></div>)}</div>}
function CustomerTable({list,open}:{list:typeof people,open:(p:typeof people[number])=>void}){return <div className="table-wrap"><table><thead><tr><th>العميل</th><th>البرنامج</th><th>قناة الشراء</th><th>حالة الأكاديمية</th><th>المسؤول</th><th>الخطوة التالية</th></tr></thead><tbody>{list.map(p=><tr key={p.id} onClick={()=>open(p)}><td><b>{p.name}</b><small>{p.id}</small></td><td><b>{p.program}</b><small>{p.track}</small></td><td>{p.source}</td><td><span className={`pill ${p.tone}`}>{p.state}</span></td><td><span className="owner"><i>{p.owner[0]}</i>{p.owner}</span></td><td>{p.due}</td></tr>)}</tbody></table></div>}
