"use client";
import { useMemo, useState } from "react";

type View="dashboard"|"work"|"customers"|"academy"|"finance"|"reports";
const nav:[View,string,string,number?][]=[["dashboard","لوحة القيادة","⌂"],["work","عملي اليوم","✓",8],["customers","العملاء والتسجيلات","◎"],["academy","عمليات الأكاديمية","◫",5],["finance","المالية والتحصيل","﷼",3],["reports","التقارير","↗"]];
const people=[
 {id:"SLK-2048",name:"سارة محمد",phone:"055 321 9840",program:"تحليل السلوك التطبيقي",track:"ABAT",source:"المتجر",owner:"ليان",state:"بانتظار التسجيل",tone:"amber",due:"متابعة اليوم، 12:30 م",paid:4250,total:6500},
 {id:"SLK-2047",name:"عمر خالد",phone:"050 918 3721",program:"إدارة السلوك التنظيمي",track:"P",source:"تسجيل مباشر",owner:"نور",state:"بانتظار الإسناد",tone:"blue",due:"منذ ساعتين",paid:8000,total:8000},
 {id:"SLK-2046",name:"ريم عبدالله",phone:"053 645 2280",program:"تحليل السلوك التطبيقي",track:"QBA",source:"المنصة",owner:"ليان",state:"تم التواصل",tone:"violet",due:"متابعة غداً",paid:3000,total:9500},
 {id:"SLK-2045",name:"فيصل أحمد",phone:"056 122 8304",program:"التعليم المستمر",track:"RBT",source:"تمارا",owner:"مها",state:"مكتمل",tone:"green",due:"لا إجراء مطلوب",paid:2400,total:2400}
];
const tasks=[
 ["09:30","التواصل مع سارة لاستكمال التسجيل","سارة محمد · SLK-2048","أكاديمية","amber"],
 ["11:00","التحقق من الدفعة الثانية","ريم عبدالله · 2,000 ر.س","مالية","red"],
 ["12:30","إسناد مقررات برنامج OBM","عمر خالد · الدفعة 18","إسناد","blue"],
 ["14:00","مراجعة طلب جديد من المتجر","نجلاء صالح · SLK-2049","مبيعات","violet"]
];
const titles:Record<View,[string,string]>={dashboard:["صباح الخير، أحمد","هذه صورة العمل الحية ليوم الثلاثاء 21 يوليو"],work:["عملي اليوم","الأولويات والمتابعات المسندة إليك"],customers:["العملاء والتسجيلات","ملف موحد لكل عميل وجميع تسجيلاته"],academy:["عمليات الأكاديمية","من الاستلام حتى التحقق من دخول المتعلم"],finance:["المالية والتحصيل","المستحقات، الدفعات وخطط الأقساط"],reports:["التقارير الإدارية","مؤشرات الأداء وجودة العمليات"]};

export default function Home(){
 const[view,setView]=useState<View>("dashboard"),[query,setQuery]=useState(""),[selected,setSelected]=useState(people[0]),[panel,setPanel]=useState(false);
 const list=useMemo(()=>people.filter(p=>`${p.name} ${p.id} ${p.program}`.includes(query)),[query]);
 const open=(p:typeof people[number])=>{setSelected(p);setPanel(true)};
 return <main className="shell" dir="rtl">
  <aside className="sidebar"><div className="brand"><i>س</i><div><b>سلوكيرا</b><span>مركز العمليات</span></div></div><div className="workspace"><i/><div><b>بيئة العمل</b><span>متصل وآمن</span></div><em>⌄</em></div><p className="nav-label">مساحة العمل</p><nav>{nav.map(([id,label,icon,badge])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><i>{icon}</i>{label}{badge&&<em>{badge}</em>}</button>)}</nav><div className="health"><span>سلامة النظام</span><b>كل الأنظمة تعمل</b><strong>99.9%</strong><i><u/></i></div><div className="profile"><i>أع</i><div><b>أحمد العلي</b><span>مدير النظام</span></div><button>⋯</button></div></aside>
  <section className="main"><header className="topbar"><b className="mobile-logo">سلوكيرا</b><label><i>⌕</i><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن عميل، رقم طلب أو برنامج..."/></label><button className="bell">♢<i/></button><button className="primary" onClick={()=>setView("customers")}>＋ تسجيل جديد</button></header><div className="content"><header className="heading"><div><h1>{titles[view][0]}</h1><p>{titles[view][1]}</p></div><span>اليوم · 21 يوليو 2026</span></header>
   {view==="dashboard"&&<Dashboard open={open}/>} {view==="work"&&<Work/>} {view==="customers"&&<Customers list={list} open={open}/>} {view==="academy"&&<Academy open={open}/>} {view==="finance"&&<Finance open={open}/>} {view==="reports"&&<Reports/>}
  </div></section>
  {panel&&<><div className="overlay" onClick={()=>setPanel(false)}/><aside className="drawer"><button className="close" onClick={()=>setPanel(false)}>×</button><div className="person"><i>{selected.name.slice(0,2)}</i><div><h2>{selected.name}</h2><p>{selected.id} · {selected.phone}</p></div></div><div className="actions"><button>واتساب</button><button>اتصال</button><button>تعديل</button></div><Section title="التسجيل الحالي"><div className="info"><label>البرنامج<b>{selected.program}</b></label><label>المسار<b>{selected.track}</b></label><label>قناة الشراء<b>{selected.source}</b></label><label>المسؤول<b>{selected.owner}</b></label></div></Section><Section title="حالة الأكاديمية"><div className={`status ${selected.tone}`}><b>{selected.state}</b><span>{selected.due}</span></div></Section><Section title="الملخص المالي"><div className="money"><p>قيمة الطلب<b>{selected.total.toLocaleString()} ر.س</b></p><p>المحصل<b>{selected.paid.toLocaleString()} ر.س</b></p></div><div className="progress"><i style={{width:`${selected.paid/selected.total*100}%`}}/></div></Section><Section title="آخر النشاطات"><div className="timeline"><p>تم تحديث حالة التسجيل<small>اليوم، 10:42 · {selected.owner}</small></p><p>تم إنشاء التسجيل في النظام<small>أمس، 16:20 · المبيعات</small></p></div></Section></aside></>}
 </main>
}

function Dashboard({open}:{open:(p:typeof people[number])=>void}){return <><div className="kpis"><Kpi title="طلبات هذا الشهر" value="128" tag="+12.5%" note="مقارنة بالشهر الماضي" tone="blue"/><Kpi title="بانتظار الأكاديمية" value="17" tag="5 عاجلة" note="تجاوزت وقت الاستلام" tone="amber"/><Kpi title="التحصيل هذا الشهر" value="184,250" tag="ر.س" note="من أصل 221,000 ر.س" tone="green"/><Kpi title="مستحقات متأخرة" value="23,500" tag="8 أقساط" note="تحتاج متابعة مالية" tone="red"/></div><div className="dashboard-grid"><Card title="الأولويات اليوم" action="عرض كل المهام"><TaskList/></Card><Card title="تدفق عمليات الأكاديمية" action="فتح لوحة الأكاديمية"><div className="flow">{[["17","جديد","gray"],["12","تم التواصل","violet"],["9","بانتظار التسجيل","amber"],["6","بانتظار الإسناد","blue"],["84","مكتمل","green"]].map(([n,l,t])=><div key={l}><i className={t}>{n}</i><span>{l}</span></div>)}</div><div className="sla"><span>متوسط إكمال التهيئة</span><b>1.8 يوم</b><em>الهدف: أقل من يومين</em></div></Card><div className="latest"><Card title="أحدث التسجيلات" action="عرض جميع التسجيلات"><CustomerTable list={people} open={open}/></Card></div><Card title="نبض التحصيل" action="التفاصيل المالية"><div className="ring"><div><b>83%</b><span>نسبة التحصيل</span></div></div><div className="legend"><p><i className="green"/>تم التحصيل<b>184,250 ر.س</b></p><p><i className="amber"/>قادم<b>13,250 ر.س</b></p><p><i className="red"/>متأخر<b>23,500 ر.س</b></p></div></Card></div></>}
function Work(){return <div className="board">{["متأخرة","اليوم","قادمة"].map((col,i)=><section key={col}><header><b>{col}</b><span>{[2,4,7][i]}</span></header>{tasks.slice(i===2?1:0,i===0?2:4).map(t=><article key={t[1]}><em className={t[4]}>{t[3]}</em><h3>{t[1]}</h3><p>{t[2]}</p><footer>◷ {t[0]}<i>{i===1?"ن":"ل"}</i></footer></article>)}</section>)}</div>}
function Customers({list,open}:{list:typeof people,open:(p:typeof people[number])=>void}){return <div className="card full"><div className="toolbar"><button className="selected">الكل <b>{list.length}</b></button><button>جدد</button><button>نشطون</button><button>مكتملون</button><button className="filter">☷ تصفية</button></div><CustomerTable list={list} open={open}/></div>}
function Academy({open}:{open:(p:typeof people[number])=>void}){return <div className="kanban">{["جديد","تم التواصل","بانتظار التسجيل","بانتظار الإسناد","مكتمل"].map((col,i)=><section key={col}><header><b>{col}</b><span>{i===4?84:[3,2,2,1][i]}</span></header>{people.filter((_,n)=>i===4?n===3:n===i).map(p=><article key={p.id} onClick={()=>open(p)}><b>{p.name}</b><small>{p.id}</small><p>{p.program}</p><em>{p.due}</em><footer><span>{p.track}</span><i>{p.owner[0]}</i></footer></article>)}</section>)}</div>}
function Finance({open}:{open:(p:typeof people[number])=>void}){return <><div className="kpis"><Kpi title="إجمالي المستحق" value="221,000" tag="ر.س" note="الشهر الحالي" tone="blue"/><Kpi title="تم التحصيل" value="184,250" tag="83%" note="من إجمالي المستحق" tone="green"/><Kpi title="قادم خلال 7 أيام" value="13,250" tag="6 أقساط" note="تذكير تلقائي مجدول" tone="amber"/><Kpi title="متأخر" value="23,500" tag="8 أقساط" note="3 تحتاج تصعيد" tone="red"/></div><Card title="متابعة الأقساط" action="تصدير التقرير"><div className="table-wrap"><table><thead><tr><th>العميل</th><th>الطلب</th><th>المبلغ</th><th>الاستحقاق</th><th>الحالة</th><th/></tr></thead><tbody>{people.map((p,i)=><tr key={p.id}><td><b>{p.name}</b><small>{p.phone}</small></td><td>{p.id}</td><td><b>{["2,250","2,000","1,500","—"][i]} ر.س</b></td><td>{["اليوم","متأخر 3 أيام","27 يوليو","مسدد"][i]}</td><td><span className={`pill ${["amber","red","blue","green"][i]}`}>{["مستحق اليوم","متأخر","قادم","مسدد"][i]}</span></td><td><button className="link" onClick={()=>open(p)}>فتح الملف</button></td></tr>)}</tbody></table></div></Card></>}
function Reports(){return <div className="reports"><Card title="التسجيلات حسب البرنامج" action="آخر 30 يوم"><div className="bars">{[["تحليل السلوك التطبيقي",74],["إدارة السلوك التنظيمي",52],["التعليم المستمر",31],["الاقتصاد السلوكي",18]].map(([n,v])=><div key={n}><span>{n}</span><i><u style={{width:`${v}%`}}/></i><b>{v}</b></div>)}</div></Card><Card title="كفاءة رحلة التسجيل" action="هذا الشهر"><div className="metric"><b>1.8</b><span>يوم متوسط التهيئة</span><em>↓ 14% تحسن</em></div><div className="mini"><p><b>4.2 س</b>أول تواصل</p><p><b>91%</b>إكمال التسجيل</p><p><b>96%</b>دقة البيانات</p></div></Card></div>}

function Kpi({title,value,tag,note,tone}:{title:string,value:string,tag:string,note:string,tone:string}){return <article className={`kpi ${tone}`}><span>{title}</span><div><b>{value}</b><em>{tag}</em></div><p>{note}</p></article>}
function Card({title,action,children}:{title:string,action:string,children:React.ReactNode}){return <section className="card"><header className="card-head"><h2>{title}</h2><button>{action} ←</button></header>{children}</section>}
function Section({title,children}:{title:string,children:React.ReactNode}){return <section className="drawer-section"><h3>{title}</h3>{children}</section>}
function TaskList(){return <div>{tasks.map(t=><div className="task" key={t[1]}><time>{t[0]}</time><i className={t[4]}/><div><b>{t[1]}</b><span>{t[2]}</span></div><em className={t[4]}>{t[3]}</em><button>⋯</button></div>)}</div>}
function CustomerTable({list,open}:{list:typeof people,open:(p:typeof people[number])=>void}){return <div className="table-wrap"><table><thead><tr><th>العميل</th><th>البرنامج</th><th>قناة الشراء</th><th>حالة الأكاديمية</th><th>المسؤول</th><th>الخطوة التالية</th></tr></thead><tbody>{list.map(p=><tr key={p.id} onClick={()=>open(p)}><td><b>{p.name}</b><small>{p.id}</small></td><td><b>{p.program}</b><small>{p.track}</small></td><td>{p.source}</td><td><span className={`pill ${p.tone}`}>{p.state}</span></td><td><span className="owner"><i>{p.owner[0]}</i>{p.owner}</span></td><td>{p.due}</td></tr>)}</tbody></table></div>}
