import { authorize, id, operationalDb } from "../_lib/operations";

export const dynamic="force-dynamic";
const validRoles=["admin","sales","finance","academy","viewer"],validPermissions=["customers.view","customers.manage","reservations.manage","programs.activate","finance.view","finance.total.edit","finance.installments.manage","finance.payments.record","reports.view","users.manage"];
const enc=new TextEncoder(),hex=(b:ArrayBuffer)=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("");
async function hashPassword(password:string,salt:string){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);return hex(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:enc.encode(salt),iterations:25000},key,256))}
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(24))).map(x=>x.toString(16).padStart(2,"0")).join("");

export async function GET(req:Request){const auth=await authorize(req,[]);if(!auth.ok)return auth.response;const {results}=await operationalDb().prepare("SELECT r.email,r.role,r.active,r.created_at,a.display_name,a.permissions,CASE WHEN a.email IS NULL THEN 0 ELSE 1 END has_password FROM staff_roles r LEFT JOIN staff_accounts a ON a.email=r.email ORDER BY r.email,r.role").all();return Response.json({staff:results,permissionOptions:validPermissions})}
export async function POST(req:Request){
 const auth=await authorize(req,[]);if(!auth.ok)return auth.response;
 const body=await req.json() as Record<string,unknown>,name=String(body.name||"").trim(),email=String(body.email||"").trim().toLowerCase(),password=String(body.password||""),active=body.active!==false,roles=(Array.isArray(body.roles)?body.roles:[body.role]).map(String).filter(x=>validRoles.includes(x)),permissions=(Array.isArray(body.permissions)?body.permissions:[]).map(String).filter(x=>validPermissions.includes(x));
 if(!name||!email||!roles.length)return Response.json({error:"اسم الموظف والبريد وصلاحية واحدة على الأقل مطلوبة"},{status:400});const db=operationalDb(),now=new Date().toISOString(),existing=await db.prepare("SELECT email FROM staff_accounts WHERE email=?").bind(email).first();if(!existing&&password.length<8)return Response.json({error:"كلمة المرور مطلوبة ويجب ألا تقل عن 8 أحرف"},{status:400});
 const statements=[db.prepare("DELETE FROM staff_roles WHERE email=?").bind(email),...roles.map(role=>db.prepare("INSERT INTO staff_roles(id,email,role,active,granted_by_email,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").bind(id("ROL"),email,role,active?1:0,auth.email,now,now))];
 if(existing)statements.push(db.prepare("UPDATE staff_accounts SET display_name=?,permissions=?,active=?,updated_at=? WHERE email=?").bind(name,JSON.stringify(permissions),active?1:0,now,email));else{const salt=random(),hash=await hashPassword(password,salt);statements.push(db.prepare("INSERT INTO staff_accounts(email,password_hash,password_salt,permissions,active,created_at,updated_at,display_name) VALUES(?,?,?,?,?,?,?,?)").bind(email,hash,salt,JSON.stringify(permissions),active?1:0,now,now,name))}if(existing&&password){if(password.length<8)return Response.json({error:"كلمة المرور يجب ألا تقل عن 8 أحرف"},{status:400});const salt=random(),hash=await hashPassword(password,salt);statements.push(db.prepare("UPDATE staff_accounts SET password_hash=?,password_salt=?,updated_at=? WHERE email=?").bind(hash,salt,now,email))}
 statements.push(db.prepare("INSERT INTO audit_log(id,actor_email,action,entity_type,entity_id,details,created_at) VALUES(?,?,'UPDATE_STAFF_ACCESS','staff_account',?,?,?)").bind(id("AUD"),auth.email,email,JSON.stringify({name,roles,permissions,active}),now));await db.batch(statements);return Response.json({ok:true,name,email,roles,permissions,active});
}
